"""
db_compat.py — SQLite <-> PostgreSQL cift-mod veritabani erisim katmani.

    DATABASE_URL env VAR  -> PostgreSQL (psycopg 3)   [uretim / yatay olcek]
    DATABASE_URL env YOK  -> SQLite  (aura.db)        [yerel gelistirme + testler]

`database.py` ve `aura_memory.py` ikisi de baglantilarini buradan alir
(`get_conn()`).  Amac cagri yerlerindeki SQL'i olabildigince degistirmemek:

  * '?' parametreleri PG'de otomatik '%s'ye cevrilir (execute sarmalayici)
  * satirlar HEM index (row[0]) HEM sutun-adi (row["x"]) ile erisilebilir;
    dict(row) her iki modda da calisir
  * cursor.lastrowid PG'de  "... RETURNING id"  enjekte edilerek taklit edilir
  * PRAGMA'lar PG'de sessizce yok sayilir
  * SQLite tarih deyimleri  datetime('now') / date('now') / date(<col>)  PG
    karsiligina cevrilir

ONEMLI: SQLite yolu BILINCLI olarak tam passthrough'dur. DATABASE_URL tanimli
DEGILKEN bu modulun davranisi, eski `sqlite3.connect(...)` kodu ile bayt-bayt
aynidir — yani bu dosyayi eklemek uretimde (PG eklenene kadar) HICBIR sey
degistirmez.
"""
import os
import re
import sqlite3

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_DIR = os.getenv("DB_DIR", BASE_DIR)
DB_PATH = os.path.join(DB_DIR, "aura.db")

_raw_url = os.getenv("DATABASE_URL", "").strip()
IS_PG = _raw_url.startswith(("postgres://", "postgresql://"))

# Railway/Heroku bazen "postgres://" verir; psycopg "postgresql://" ister.
DATABASE_URL = _raw_url
if IS_PG and DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = "postgresql://" + DATABASE_URL[len("postgres://"):]


def backend_name() -> str:
    return "postgresql" if IS_PG else "sqlite"


# ======================================================================
# SQLite yolu  —  tam passthrough (davranis degismez)
# ======================================================================
if not IS_PG:

    # database.py / aura_memory.py bunlari `except db_compat.OperationalError`
    # / `except db_compat.IntegrityError` seklinde yakalar — SQLite'ta eski
    # `sqlite3.*` ile bire bir ayni sinif.
    OperationalError = sqlite3.OperationalError
    IntegrityError = sqlite3.IntegrityError

    def get_conn():
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA busy_timeout = 5000")
        conn.execute("PRAGMA journal_mode = WAL")
        return conn


# ======================================================================
# PostgreSQL yolu  —  psycopg 3 uzerine ince uyumluluk sarmalayicisi
# ======================================================================
else:
    import datetime as _dt
    import decimal as _decimal

    import psycopg
    import psycopg.errors as _pgerr

    # database.py / aura_memory.py'nin `except db_compat.*` bloklari icin.
    # Genis tutuldu: bu bloklar hep "idempotent migration guard" veya
    # "yaris kosulunda UNIQUE ihlali" — PG'de DuplicateColumn/DuplicateTable/
    # UniqueViolation hepsi ilgili ust sinifin altinda.
    OperationalError = _pgerr.Error
    IntegrityError = _pgerr.IntegrityError

    # --- SQL cevirisi ------------------------------------------------------
    # Sirali uygulanir; ozel ('now') kaliplari once, genel date(<x>) sonra.
    _SQL_SUBS = [
        # datetime('now') -> gercek UTC timestamp (expires_at TIMESTAMP ile
        # karsilastiriliyor).
        (re.compile(r"datetime\(\s*'now'\s*\)", re.I),
         "(now() AT TIME ZONE 'utc')"),
        # date('now') VE date(<kolon>) -> HER IKISI DE 'YYYY-MM-DD' METNI.
        # Neden metin: bu sorgularin bir tarafi TEXT kolon (usage_date),
        # digeri TIMESTAMP kolon (created_at/timestamp) ya da TEXT ISO
        # (event_at). PG "date <op> text" icin implicit cast YAPMAZ (sadece
        # unknown literal icin yapar) -> "operator does not exist" hatasi.
        # Iki tarafi da to_char ile metne cevirince 'YYYY-MM-DD' leksik
        # siralamasi = kronolojik siralama, tum karsilastirmalar calisir.
        (re.compile(r"date\(\s*'now'\s*\)", re.I),
         "to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD')"),
        (re.compile(r"\bdate\(\s*([A-Za-z_][A-Za-z0-9_.]*)\s*\)", re.I),
         r"to_char((\1)::timestamp, 'YYYY-MM-DD')"),
        # ALTER TABLE ... ADD COLUMN -> IF NOT EXISTS (PG destekler, SQLite
        # etmez). Boylece migration'lar PG'de HIC exception atmaz -> tek
        # transaction icindeki "current transaction is aborted" zinciri olmaz.
        (re.compile(r"\bADD\s+COLUMN\s+(?!IF\s+NOT\s+EXISTS)", re.I),
         "ADD COLUMN IF NOT EXISTS "),
        # SQLite'a ozgu:
        (re.compile(r"PRAGMA[^;]*;?", re.I), ""),
        (re.compile(r"\bAUTOINCREMENT\b", re.I), ""),
        (re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\b", re.I),
         "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
        (re.compile(r"\bINSERT\s+OR\s+IGNORE\b", re.I), "INSERT"),
    ]

    def _translate_sql(sql: str) -> str:
        for rx, repl in _SQL_SUBS:
            sql = rx.sub(repl, sql)
        # '?' -> '%s'  (bu kod tabaninda '?' yalnizca bind parametresi olarak
        # gecer; string literal icinde '?' yok — dogrulandi 2026-09-06).
        sql = sql.replace("?", "%s")
        return sql

    def _coerce(v):
        """PG'nin dondurdugu tipleri SQLite'in dondurdugune yaklastir:
        timestamp/date -> ISO metin (SQLite CURRENT_TIMESTAMP formati),
        Decimal -> int/float. Boylece cagri yerleri (JSON serilestirme,
        string karsilastirma) degismeden calisir."""
        if isinstance(v, _dt.datetime):
            return v.isoformat(sep=" ", timespec="seconds")
        if isinstance(v, _dt.date):
            return v.isoformat()
        if isinstance(v, _decimal.Decimal):
            f = float(v)
            return int(f) if f.is_integer() else f
        return v

    _INSERT_RE = re.compile(r"^\s*INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)", re.I)
    _RETURNING_RE = re.compile(r"\bRETURNING\b", re.I)

    class _Row(dict):
        """dict + pozisyonel erisim.  row[0], row['x'], dict(row) hepsi calisir."""
        __slots__ = ("_vals",)

        def __init__(self, cols, vals):
            vals = [_coerce(v) for v in vals]
            super().__init__(zip(cols, vals))
            self._vals = vals

        def __getitem__(self, k):
            if isinstance(k, int):
                return self._vals[k]
            return super().__getitem__(k)

    def _row_factory(cur):
        cols = [d.name for d in cur.description] if cur.description else []
        def make(vals):
            return _Row(cols, vals)
        return make

    class _Cursor:
        """sqlite3.Cursor benzeri; ? -> %s cevirir, lastrowid'i RETURNING ile verir."""

        def __init__(self, raw):
            self._c = raw
            self.lastrowid = None

        def execute(self, sql, params=()):
            tsql = _translate_sql(sql)
            m = _INSERT_RE.match(tsql)
            want_id = m and not _RETURNING_RE.search(tsql)
            if want_id:
                tsql = tsql.rstrip().rstrip(";") + " RETURNING id"
            self._c.execute(tsql, tuple(params) if params else None)
            if want_id:
                try:
                    row = self._c.fetchone()
                    self.lastrowid = row[0] if row else None
                except Exception:
                    self.lastrowid = None
            return self

        def executemany(self, sql, seq):
            self._c.executemany(_translate_sql(sql), list(seq))
            return self

        def fetchone(self):
            return self._c.fetchone()

        def fetchall(self):
            return self._c.fetchall()

        @property
        def description(self):
            return self._c.description

        @property
        def rowcount(self):
            return self._c.rowcount

        def close(self):
            self._c.close()

    class _Conn:
        """sqlite3.Connection benzeri kabuk: .cursor(), .execute(), .commit(),
        .close().  .close() baglantiyi KAPATMAZ — havuza geri verir."""

        def __init__(self, raw):
            self._conn = raw
            self._returned = False

        def cursor(self):
            return _Cursor(self._conn.cursor(row_factory=_row_factory))

        def execute(self, sql, params=()):
            cur = self.cursor()
            cur.execute(sql, params)
            return cur

        def commit(self):
            self._conn.commit()

        def rollback(self):
            self._conn.rollback()

        def close(self):
            # db_cursor() her zaman finally'de cagirir. Havuz, geri verilen
            # baglantidaki acik transaction'i kendisi rollback eder.
            if self._returned:
                return
            self._returned = True
            try:
                _POOL.putconn(self._conn)
            except Exception:
                try:
                    self._conn.close()
                except Exception:
                    pass

    # Baglanti havuzu — SQLite'ta connect ~bedava, PG'de her istekte yeni
    # TCP+TLS+auth el sikismasi hem yavas hem PG'nin max_connections'ini
    # tuketir. Havuz, worker basina birkac baglantiyi tekrar kullanir.
    from psycopg_pool import ConnectionPool

    _POOL = ConnectionPool(
        DATABASE_URL,
        min_size=1,
        max_size=int(os.getenv("PG_POOL_MAX", "10")),
        max_idle=60,
        kwargs={"autocommit": False},
        open=True,
    )

    def get_conn():
        return _Conn(_POOL.getconn())
